### ISSUE TITLE
[FEATURE] Send post notification only to the creator of the post

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/groups-building-block#372] opened 2023-04-25 11:34 UTC
**Is your feature request related to a problem? Please describe.**
This issue is consequent of https://github.com/rokwire/illinois-app/issues/2938 .

**Describe the solution you'd like**
In Groups when a new reply is created then send a notification only to the creator of the main post (not to all group members)

**Update 2024/05/08**:
Notify only the post creator and the users in the post thread but not all group members. For references, please see the updated issue: https://github.com/rokwire/illinois-app/issues/2938#issuecomment-2099201189

**Comment by mihail-varbanov** [comment] 2024-05-20 08:08
This is not a duplicate of #457.

**Closed** 2024-06-24 13:29 UTC
Labels: enhancement
